[package]
name = "tox"
version = "0.0.1"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]


[dependencies.linenoise-rust]
# linenoise-rust = "0.1.2"
git = "https://github.com/octplane/rust-linenoise.git"
