[package]
name = "lexers"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
version = "0.0.5"
description = "Various string tokenizers"
license = "MIT"
repository = "https://github.com/rodolf0/tox"
