[package]
name = "lexers"
version = "0.0.8"
edition = "2018"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "Various string tokenizers"
license = "MIT"
repository = "https://github.com/rodolf0/tox"
