[package]
name = "lisp"
version = "0.0.3"
edition = "2018"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "A lisp like thingy"

[dependencies]
lexers = { version = "0.1.2", path = "../lexers" }
rustyline = "1.0.0"
