[package]
name = "earlgrey"
version = "0.0.4"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "An earley parser library"
license = "MIT"
repository = "https://github.com/rodolf0/tox"

[dependencies]
lexers = { version = "0.0.4", path = "../lexers" }

[[example]]
name = "arith"
path = "examples/arith.rs"

[dev-dependencies]
linenoise-rust = "0.2"
regex = "0.1"
