[package]
name = "earlgrey"
version = "0.2.2"
edition = "2018"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "An earley parser library"
license = "MIT"
repository = "https://github.com/rodolf0/tox"

[features]
debug = []

[[example]]
name = "arith"
path = "examples/arith.rs"

[dev-dependencies]
lexers = { version = "0.0.7", path = "../lexers" }
rustyline = "1.0.0"
