[package]
name = "earlgrey"
version = "0.1.0"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "An earley parser library"
license = "MIT"
repository = "https://github.com/rodolf0/tox"

[[example]]
name = "arith"
path = "examples/arith.rs"

[dev-dependencies]
rustyline = "1.0.0"
lexers = { version = "0.0.5", path = "../lexers" }
