[package]
name = "shunting"
version = "0.0.3"
edition = "2018"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "A shunting-yard math parser"
license = "MIT"
repository = "https://github.com/rodolf0/tox"

[features]
default = ["dynlink-eval"]
dynlink-eval = ["dylib"]

[dependencies]
lexers = { version = "0.0.7", path = "../lexers" }
rustyline = "3.0.0"
rand = "0.6"

[dependencies.dylib]
version = "0.0.3"
optional = true
