[package]
name = "shunting"
version = "0.0.3"
authors = ["Rodolfo Granata <warlock.cc@gmail.com>"]
description = "A shunting-yard math parser"

[features]
default = ["dynlink-eval"]
dynlink-eval = ["dylib"]

[dependencies]
lexers = { version = "0.0.4", path = "../lexers" }
linenoise-rust = "0.2.0"
rand = "0.3"

[dependencies.dylib]
version = "0.0.2"
optional = true
